---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordstream-producer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app:  wordstream-producer
    spec:
      containers:
      - name: wordstream-producer
        image: localhost:5000/wordstream-producer
        ports:
        - containerPort: 3000
    env:
      - name: REDIS_HOST
        value: "redis-master"
      - name: REDIS_PORT
        value: "6379"
      - name: REDIS_PWD
        value: "none"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordstream-consumer
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app:  wordstream-consumer
    spec:
      containers:
        - name: wordstream-consumer
          image: localhost:5000/wordstream-consumer
          ports:
            - containerPort: 3000
      env:
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PWD
          value: "none"