kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: pinger
    image: reselbob/pinger
    env:
    - name: SUPER_SECRET_USERNAME
       valueFrom:
         secretKeyRef:
           name: mysecret
           key: username
    - name: SUPER_SECRET_PWD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password